/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "index": {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    meta: undefined,
  },
  "animated-mobile-navbar": {
    name: "animated-mobile-navbar",
    description: "A simple animated mobile navbar component.",
    type: "registry:component",
    registryDependencies: ["button"],
    files: [{
      path: "registry/react/atlasui/animated-mobile-navbar.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/atlasui/animated-mobile-navbar.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "project-gallery": {
    name: "project-gallery",
    description: "A Project Gallery with an interactive modal.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/react/atlasui/project-gallery.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/atlasui/project-gallery.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "parallax-sections": {
    name: "parallax-sections",
    description: "A simple Parallax effect using Motion.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/react/atlasui/parallax-sections.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/atlasui/parallax-sections.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "shiny-button": {
    name: "shiny-button",
    description: "A shiny button with a sleek animation effect.",
    type: "registry:ui",
    registryDependencies: ["utils"],
    files: [{
      path: "registry/react/atlasui/shiny-button.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/atlasui/shiny-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "dot-and-circle-mouse-trailer": {
    name: "dot-and-circle-mouse-trailer",
    description: "A simple Lazy Dot and Circle Mouse Trailer",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/react/atlasui/dot-and-circle-mouse-trailer.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/atlasui/dot-and-circle-mouse-trailer.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "blob-mouse-trailer": {
    name: "blob-mouse-trailer",
    description: "A simple Lazy Blob Mouse Trailer",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/react/atlasui/blob-mouse-trailer.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/atlasui/blob-mouse-trailer.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "blend-mouse-trailer": {
    name: "blend-mouse-trailer",
    description: "A simple Lazy Mouse Trailer which blends with the content on hover.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/react/atlasui/blend-mouse-trailer.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/atlasui/blend-mouse-trailer.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "hacker-text": {
    name: "hacker-text",
    description: "A text animation that scrambles letters before revealing the final text.",
    type: "registry:component",
    registryDependencies: ["utils"],
    files: [{
      path: "registry/react/atlasui/hacker-text.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/atlasui/hacker-text.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "scroll-based-text-reveal": {
    name: "scroll-based-text-reveal",
    description: "A text reveal effect which animates the opacity of the text as you scroll.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/react/atlasui/scroll-based-text-reveal.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/atlasui/scroll-based-text-reveal.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "scroll-based-word-reveal": {
    name: "scroll-based-word-reveal",
    description: "A text reveal effect which progressively reveals text word by word as you scroll.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/react/atlasui/scroll-based-word-reveal.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/atlasui/scroll-based-word-reveal.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "scroll-based-character-reveal": {
    name: "scroll-based-character-reveal",
    description: "A text reveal effect which progressively reveals text character by character as you scroll.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/react/atlasui/scroll-based-character-reveal.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/atlasui/scroll-based-character-reveal.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "reveal-effect": {
    name: "reveal-effect",
    description: "Animates content into view with a vertical slide, blur fade-in, and clipping reveal effect.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/react/atlasui/reveal-effect.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/atlasui/reveal-effect.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "loki-text-effect": {
    name: "loki-text-effect",
    description: "The iconic text animation from the Loki series intro.",
    type: "registry:component",
    registryDependencies: ["utils"],
    files: [{
      path: "registry/react/atlasui/loki-text-effect.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/fonts/font.ts",
      type: "registry:file",
      target: "~/fonts/font.ts"
    },{
      path: "registry/fonts/fontOne.woff2",
      type: "registry:file",
      target: "app/fonts/fontOne.woff2"
    },{
      path: "registry/fonts/fontTwo.woff2",
      type: "registry:file",
      target: "app/fonts/fontTwo.woff2"
    },{
      path: "registry/fonts/fontThree.woff2",
      type: "registry:file",
      target: "app/fonts/fontThree.woff2"
    },{
      path: "registry/fonts/fontFour.woff2",
      type: "registry:file",
      target: "app/fonts/fontFour.woff2"
    },{
      path: "registry/fonts/fontFive.woff2",
      type: "registry:file",
      target: "app/fonts/fontFive.woff2"
    },{
      path: "registry/fonts/fontSix.woff2",
      type: "registry:file",
      target: "app/fonts/fontSix.woff2"
    },{
      path: "registry/fonts/fontSeven.woff2",
      type: "registry:file",
      target: "app/fonts/fontSeven.woff2"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/atlasui/loki-text-effect.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "box-reveal": {
    name: "box-reveal",
    description: "A smooth reveal animation that slides a colored overlay away to introduce content as it enters the viewport.",
    type: "registry:component",
    registryDependencies: ["utils"],
    files: [{
      path: "registry/react/atlasui/box-reveal.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/atlasui/box-reveal.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "notch-nav": {
    name: "notch-nav",
    description: "A Notch style trigger that reveals the navigation menu from above.",
    type: "registry:component",
    registryDependencies: ["utils"],
    files: [{
      path: "registry/react/atlasui/notch-nav.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/atlasui/notch-nav.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "animated-mobile-navbar-demo": {
    name: "animated-mobile-navbar-demo",
    description: "Example showcasing the Animated Mobile Navbar component.",
    type: "registry:example",
    registryDependencies: ["https://atlasui.vercel.app/r/animated-mobile-navbar.json"],
    files: [{
      path: "registry/react/examples/animated-mobile-navbar-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/examples/animated-mobile-navbar-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "animated-mobile-navbar-side-example": {
    name: "animated-mobile-navbar-side-example",
    description: "Example showcasing the Mobile Navbar emerging from the side.",
    type: "registry:example",
    registryDependencies: ["https://atlasui.vercel.app/r/animated-mobile-navbar.json"],
    files: [{
      path: "registry/react/examples/animated-mobile-navbar-side-example.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/examples/animated-mobile-navbar-side-example.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "project-gallery-demo": {
    name: "project-gallery-demo",
    description: "Example of Project Gallery with an interactive modal.",
    type: "registry:example",
    registryDependencies: ["https://atlasui.vercel.app/r/project-gallery.json"],
    files: [{
      path: "registry/react/examples/project-gallery-demo.tsx",
      type: "registry:example",
      target: "components/project-gallery-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/examples/project-gallery-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "parallax-sections-demo": {
    name: "parallax-sections-demo",
    description: "Example of Parallax Sections component.",
    type: "registry:example",
    registryDependencies: ["https://atlasui.vercel.app/r/parallax-sections.json"],
    files: [{
      path: "registry/react/examples/parallax-sections-demo.tsx",
      type: "registry:example",
      target: "components/parallax-sections-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/examples/parallax-sections-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "shiny-button-demo": {
    name: "shiny-button-demo",
    description: "Example of Shiny Button with a sleek animation effect.",
    type: "registry:example",
    registryDependencies: ["https://atlasui.vercel.app/r/shiny-button.json"],
    files: [{
      path: "registry/react/examples/shiny-button-demo.tsx",
      type: "registry:example",
      target: "components/shiny-button-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/examples/shiny-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "dot-and-circle-mouse-trailer-demo": {
    name: "dot-and-circle-mouse-trailer-demo",
    description: "Example showing the lazy dot and circle that follows the mouse cursor.",
    type: "registry:example",
    registryDependencies: ["https://atlasui.vercel.app/r/dot-and-circle-mouse-trailer.json"],
    files: [{
      path: "registry/react/examples/dot-and-circle-mouse-trailer-demo.tsx",
      type: "registry:example",
      target: "components/dot-and-circle-mouse-trailer-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/examples/dot-and-circle-mouse-trailer-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "blob-mouse-trailer-demo": {
    name: "blob-mouse-trailer-demo",
    description: "Example showing the lazy blob that follows the mouse cursor.",
    type: "registry:example",
    registryDependencies: ["https://atlasui.vercel.app/r/blob-mouse-trailer.json"],
    files: [{
      path: "registry/react/examples/blob-mouse-trailer-demo.tsx",
      type: "registry:example",
      target: "components/blob-mouse-trailer-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/examples/blob-mouse-trailer-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "blend-mouse-trailer-demo": {
    name: "blend-mouse-trailer-demo",
    description: "Example showing the lazy mouse trailer which blends with the content on hover.",
    type: "registry:example",
    registryDependencies: ["https://atlasui.vercel.app/r/blend-mouse-trailer.json"],
    files: [{
      path: "registry/react/examples/blend-mouse-trailer-demo.tsx",
      type: "registry:example",
      target: "components/blend-mouse-trailer-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/examples/blend-mouse-trailer-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "hacker-text-demo": {
    name: "hacker-text-demo",
    description: "Example showcasing text animation that scrambles letters before revealing the final text",
    type: "registry:example",
    registryDependencies: ["https://atlasui.vercel.app/r/hacker-text.json"],
    files: [{
      path: "registry/react/examples/hacker-text-demo.tsx",
      type: "registry:example",
      target: "components/hacker-text-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/examples/hacker-text-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "scroll-based-text-reveal-demo": {
    name: "scroll-based-text-reveal-demo",
    description: "Example showcasing a text reveal effect which animates the opacity of the text as you scroll.",
    type: "registry:example",
    registryDependencies: ["https://atlasui.vercel.app/r/scroll-based-text-reveal.json"],
    files: [{
      path: "registry/react/examples/scroll-based-text-reveal-demo.tsx",
      type: "registry:example",
      target: "components/scroll-based-text-reveal-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/examples/scroll-based-text-reveal-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "scroll-based-word-reveal-demo": {
    name: "scroll-based-word-reveal-demo",
    description: "Example showcasing a word reveal effect which animates the opacity of the word as you scroll.",
    type: "registry:example",
    registryDependencies: ["https://atlasui.vercel.app/r/scroll-based-word-reveal.json"],
    files: [{
      path: "registry/react/examples/scroll-based-word-reveal-demo.tsx",
      type: "registry:example",
      target: "components/scroll-based-word-reveal-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/examples/scroll-based-word-reveal-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "scroll-based-character-reveal-demo": {
    name: "scroll-based-character-reveal-demo",
    description: "Example showcasing a character reveal effect which animates the opacity of the character as you scroll.",
    type: "registry:example",
    registryDependencies: ["https://atlasui.vercel.app/r/scroll-based-character-reveal.json"],
    files: [{
      path: "registry/react/examples/scroll-based-character-reveal-demo.tsx",
      type: "registry:example",
      target: "components/scroll-based-character-reveal-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/examples/scroll-based-character-reveal-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "reveal-effect-demo": {
    name: "reveal-effect-demo",
    description: "Example of Reveal Effect with a vertical slide, blur fade-in, and clipping reveal effect.",
    type: "registry:example",
    registryDependencies: ["https://atlasui.vercel.app/r/reveal-effect.json"],
    files: [{
      path: "registry/react/examples/reveal-effect-demo.tsx",
      type: "registry:example",
      target: "components/reveal-effect-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/examples/reveal-effect-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "reveal-effect-speed-example": {
    name: "reveal-effect-speed-example",
    description: "Example of Reveal Effect with a custom speed.",
    type: "registry:example",
    registryDependencies: ["https://atlasui.vercel.app/r/reveal-effect.json"],
    files: [{
      path: "registry/react/examples/reveal-effect-speed-example.tsx",
      type: "registry:example",
      target: "components/reveal-effect-speed-example.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/examples/reveal-effect-speed-example.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "reveal-effect-delay-example": {
    name: "reveal-effect-delay-example",
    description: "Example of Reveal Effect with a custom delay.",
    type: "registry:example",
    registryDependencies: ["https://atlasui.vercel.app/r/reveal-effect.json"],
    files: [{
      path: "registry/react/examples/reveal-effect-delay-example.tsx",
      type: "registry:example",
      target: "components/reveal-effect-delay-example.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/examples/reveal-effect-delay-example.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "reveal-effect-translate-y-example": {
    name: "reveal-effect-translate-y-example",
    description: "Example of Reveal Effect with a custom translate-y.",
    type: "registry:example",
    registryDependencies: ["https://atlasui.vercel.app/r/reveal-effect.json"],
    files: [{
      path: "registry/react/examples/reveal-effect-translate-y-example.tsx",
      type: "registry:example",
      target: "components/reveal-effect-translate-y-example.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/examples/reveal-effect-translate-y-example.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "loki-text-effect-demo": {
    name: "loki-text-effect-demo",
    description: "Example showcasing the iconic animation from the Loki series intro.",
    type: "registry:example",
    registryDependencies: ["https://atlasui.vercel.app/r/loki-text-effect.json"],
    files: [{
      path: "registry/react/examples/loki-text-effect-demo.tsx",
      type: "registry:example",
      target: "components/loki-text-effect-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/examples/loki-text-effect-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "box-reveal-demo": {
    name: "box-reveal-demo",
    description: "Example of Box Reveal that has a smooth reveal animation that slides a colored overlay away to introduce content as it enters the viewport.",
    type: "registry:example",
    registryDependencies: ["https://atlasui.vercel.app/r/box-reveal.json"],
    files: [{
      path: "registry/react/examples/box-reveal-demo.tsx",
      type: "registry:example",
      target: "components/box-reveal-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/examples/box-reveal-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "notch-nav-demo": {
    name: "notch-nav-demo",
    description: "Example of Notch style trigger that reveals the navigation menu from above.",
    type: "registry:example",
    registryDependencies: ["https://atlasui.vercel.app/r/notch-nav.json"],
    files: [{
      path: "registry/react/examples/notch-nav-demo.tsx",
      type: "registry:example",
      target: "components/notch-nav-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/examples/notch-nav-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [{
      path: "registry/react/lib/utils.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/lib/utils.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  }