/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
  index: {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    meta: undefined,
  },
  "animated-mobile-navbar": {
    name: "animated-mobile-navbar",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button"],
    files: [
      {
        path: "registry/react/atlasui/animated-mobile-navbar.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/atlasui/animated-mobile-navbar.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "project-gallery": {
    name: "project-gallery",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/react/atlasui/project-gallery.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/atlasui/project-gallery.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "parallax-sections": {
    name: "parallax-sections",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/react/atlasui/parallax-sections.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/atlasui/parallax-sections.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "shiny-button": {
    name: "shiny-button",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button"],
    files: [
      {
        path: "registry/react/atlasui/shiny-button.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/atlasui/shiny-button.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "dot-and-circle-mouse-trailer": {
    name: "dot-and-circle-mouse-trailer",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/react/atlasui/dot-and-circle-mouse-trailer.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/atlasui/dot-and-circle-mouse-trailer.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "blob-mouse-trailer": {
    name: "blob-mouse-trailer",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/react/atlasui/blob-mouse-trailer.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/atlasui/blob-mouse-trailer.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "blend-mouse-trailer": {
    name: "blend-mouse-trailer",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/react/atlasui/blend-mouse-trailer.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/atlasui/blend-mouse-trailer.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "hacker-text": {
    name: "hacker-text",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/react/atlasui/hacker-text.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/atlasui/hacker-text.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "scroll-based-text-reveal": {
    name: "scroll-based-text-reveal",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/react/atlasui/scroll-based-text-reveal.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/atlasui/scroll-based-text-reveal.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "scroll-based-word-reveal": {
    name: "scroll-based-word-reveal",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/react/atlasui/scroll-based-word-reveal.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/atlasui/scroll-based-word-reveal.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "scroll-based-character-reveal": {
    name: "scroll-based-character-reveal",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/react/atlasui/scroll-based-character-reveal.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/atlasui/scroll-based-character-reveal.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "reveal-effect": {
    name: "reveal-effect",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/react/atlasui/reveal-effect.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/atlasui/reveal-effect.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "loki-text-effect": {
    name: "loki-text-effect",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/react/atlasui/loki-text-effect.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/react/atlasui/loki-text-effect.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "animated-mobile-navbar-demo": {
    name: "animated-mobile-navbar-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["animated-mobile-navbar"],
    files: [
      {
        path: "registry/react/examples/animated-mobile-navbar-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/examples/animated-mobile-navbar-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "animated-mobile-navbar-side-example": {
    name: "animated-mobile-navbar-side-example",
    description: "",
    type: "registry:example",
    registryDependencies: ["animated-mobile-navbar"],
    files: [
      {
        path: "registry/react/examples/animated-mobile-navbar-side-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/examples/animated-mobile-navbar-side-example.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "project-gallery-demo": {
    name: "project-gallery-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["project-gallery"],
    files: [
      {
        path: "registry/react/examples/project-gallery-demo.tsx",
        type: "registry:example",
        target: "components/project-gallery-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/examples/project-gallery-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "parallax-sections-demo": {
    name: "parallax-sections-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["parallax-sections"],
    files: [
      {
        path: "registry/react/examples/parallax-sections-demo.tsx",
        type: "registry:example",
        target: "components/parallax-sections-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/examples/parallax-sections-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "shiny-button-demo": {
    name: "shiny-button-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["shiny-button"],
    files: [
      {
        path: "registry/react/examples/shiny-button-demo.tsx",
        type: "registry:example",
        target: "components/shiny-button-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/examples/shiny-button-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "dot-and-circle-mouse-trailer-demo": {
    name: "dot-and-circle-mouse-trailer-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["dot-and-circle-mouse-trailer"],
    files: [
      {
        path: "registry/react/examples/dot-and-circle-mouse-trailer-demo.tsx",
        type: "registry:example",
        target: "components/dot-and-circle-mouse-trailer-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/examples/dot-and-circle-mouse-trailer-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "blob-mouse-trailer-demo": {
    name: "blob-mouse-trailer-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["blob-mouse-trailer"],
    files: [
      {
        path: "registry/react/examples/blob-mouse-trailer-demo.tsx",
        type: "registry:example",
        target: "components/blob-mouse-trailer-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/examples/blob-mouse-trailer-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "blend-mouse-trailer-demo": {
    name: "blend-mouse-trailer-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["blend-mouse-trailer"],
    files: [
      {
        path: "registry/react/examples/blend-mouse-trailer-demo.tsx",
        type: "registry:example",
        target: "components/blend-mouse-trailer-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/examples/blend-mouse-trailer-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "hacker-text-demo": {
    name: "hacker-text-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["hacker-text"],
    files: [
      {
        path: "registry/react/examples/hacker-text-demo.tsx",
        type: "registry:example",
        target: "components/hacker-text-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/examples/hacker-text-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "scroll-based-text-reveal-demo": {
    name: "scroll-based-text-reveal-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["scroll-based-text-reveal"],
    files: [
      {
        path: "registry/react/examples/scroll-based-text-reveal-demo.tsx",
        type: "registry:example",
        target: "components/scroll-based-text-reveal-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/examples/scroll-based-text-reveal-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "scroll-based-word-reveal-demo": {
    name: "scroll-based-word-reveal-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["scroll-based-word-reveal"],
    files: [
      {
        path: "registry/react/examples/scroll-based-word-reveal-demo.tsx",
        type: "registry:example",
        target: "components/scroll-based-word-reveal-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/examples/scroll-based-word-reveal-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "scroll-based-character-reveal-demo": {
    name: "scroll-based-character-reveal-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["scroll-based-character-reveal"],
    files: [
      {
        path: "registry/react/examples/scroll-based-character-reveal-demo.tsx",
        type: "registry:example",
        target: "components/scroll-based-character-reveal-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/examples/scroll-based-character-reveal-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "reveal-effect-demo": {
    name: "reveal-effect-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["reveal-effect"],
    files: [
      {
        path: "registry/react/examples/reveal-effect-demo.tsx",
        type: "registry:example",
        target: "components/reveal-effect-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/examples/reveal-effect-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "reveal-effect-speed-example": {
    name: "reveal-effect-speed-example",
    description: "",
    type: "registry:example",
    registryDependencies: ["reveal-effect"],
    files: [
      {
        path: "registry/react/examples/reveal-effect-speed-example.tsx",
        type: "registry:example",
        target: "components/reveal-effect-speed-example.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/examples/reveal-effect-speed-example.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "reveal-effect-delay-example": {
    name: "reveal-effect-delay-example",
    description: "",
    type: "registry:example",
    registryDependencies: ["reveal-effect"],
    files: [
      {
        path: "registry/react/examples/reveal-effect-delay-example.tsx",
        type: "registry:example",
        target: "components/reveal-effect-delay-example.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/examples/reveal-effect-delay-example.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "reveal-effect-translate-y-example": {
    name: "reveal-effect-translate-y-example",
    description: "",
    type: "registry:example",
    registryDependencies: ["reveal-effect"],
    files: [
      {
        path: "registry/react/examples/reveal-effect-translate-y-example.tsx",
        type: "registry:example",
        target: "components/reveal-effect-translate-y-example.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/examples/reveal-effect-translate-y-example.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "loki-text-effect-demo": {
    name: "loki-text-effect-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["loki-text-effect"],
    files: [
      {
        path: "registry/react/examples/loki-text-effect-demo.tsx",
        type: "registry:example",
        target: "components/loki-text-effect-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/react/examples/loki-text-effect-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
};
